spring:
  application:
    name: feign
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:2001/eureka,http://127.0.0.1:2002/eureka,http://127.0.0.1:2003/eureka
server:
  port: 3001
feign:
  hystrix:
    enabled: true
management:
  endpoints:
    web:
      exposure:
        include: "hystrix.stream"