spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql:///ygnbdsjk?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8
    username: root
    password: root
    type : com.alibaba.druid.pool.DruidDataSource
    dbcp2:
      max-wait-millis: 5000
  thymeleaf:
    prefix: classpath:/templates/pages/
    suffix: .html
  #mybatis
  aop:
    proxy-target-class: true
  http:
    encoding:
      force: true
      charset: UTF-8
      enabled: true
  redis:
    port: 6379
    host: 192.168.157.128
  application:
    name: vip
mybatis:
  configuration:
    default-statement-timeout: 30
    map-underscore-to-camel-case: true
  mapper-locations:
    - classpath:/mapper/sys/*Mapper.xml
management:
  endpoints:
    web:
      exposure:
        include: "hystrix.stream"
  #Log
logging:
  level:
    com.cy: debug
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:2001/eureka,http:127.0.0.1:2002/eureka,http:127.0.0.1:2003/eureka
---
server:
  port: 8007
spring:
  profiles: vip1
---
spring:
  profiles: vip2
server:
  port: 8008
